Jeudfra-Beta/Models/Policy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Jeudfra_Beta.Models
{
    public class Policy
    {
     
        public int Id { get; set; }
        public string Name { get; set; }
        public int Amount { get; set; }
    }
}

Jeudfra-Beta/Controllers/Api/PoliciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using Jeudfra_Beta.Models;
using Jeudfra_Beta.Dtos;
using AutoMapper;

namespace Jeudfra_Beta.Controllers.Api
{
    public class PoliciesController : ApiController
    {
        private ApplicationDbContext _context;

        public PoliciesController()
        {
            _context = new ApplicationDbContext();

        }
        //GET /api/Policies
        public IEnumerable<PolicyDto> GetPolicies()
        {
            return _context.Policies.ToList().Select(Mapper.Map<Policy, PolicyDto>);
        }

        //GET /api/Policies/1
        public IHttpActionResult GetPolicy(int id)
        {
            var policy = _context.Policies.SingleOrDefault(c => c.Id == id);
            if (policy == null)
                return NotFound();
            return Ok(Mapper.Map<Policy, PolicyDto>(policy));
        }

        //POST /api/Policies
        [HttpPost]
        public IHttpActionResult CreatePolicy(PolicyDto customerDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var policy = Mapper.Map<PolicyDto, Policy>(customerDto);
            _context.Policies.Add(policy);
            _context.SaveChanges();

            customerDto.Id = policy.Id;
            return Created(new Uri(Request.RequestUri + "/" + policy.Id), customerDto);
        }

        //PUT /api/Policies/1
        [HttpPut]
        public IHttpActionResult UpdateCustomer(int id, PolicyDto policyDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var policyinDb = _context.Policies.SingleOrDefault(c => c.Id == id);

            if (policyinDb == null)
                return NotFound();

            Mapper.Map(policyDto, policyinDb);
            
     

            _context.SaveChanges();
            return Ok();
        }

        //DELETE /api/Policies/1
        [HttpDelete]
        public IHttpActionResult DeleteCustomer(int id)
        {
            var policyinDb = _context.Policies.SingleOrDefault(c => c.Id == id);

            if (policyinDb == null)
                return NotFound();

            _context.Policies.Remove(policyinDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Jeudfra-Beta/Controllers/PolicyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Jeudfra_Beta.Models;

namespace Jeudfra_Beta.Controllers
{
    public class PolicyController : Controller
    {
        private ApplicationDbContext _context;
        // GET: Policy/Random
        public PolicyController()
        {
            _context = new ApplicationDbContext();

        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        public ViewResult Random()
        {
            var policies = _context.Policies.ToList();
            return View(policies);
           
        }
        public ActionResult Details(int id)
        {
            var policy = _context.Policies.SingleOrDefault(c => c.Id == id);
            if (policy == null)
                return HttpNotFound();

            return View(policy);
        }
    }
}

Jeudfra-Beta/Views/Policy/Details.cshtml
@model Jeudfra_Beta.Models.Policy
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>@Model.Name</h2>*@
<p>@Model.Id</p>
<p>@Model.Name</p>
<p>@Model.Amount</p>

Jeudfra-Beta/Views/Policy/Random.cshtml
@using System.Web.Mvc.Html
@model IEnumerable<Jeudfra_Beta.Models.Policy>

@{
    ViewBag.Title = "Policy Page";
}
<header id="main-header" class="py2 bg-success text-white">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1><i class="fa fa-users"></i> Policies</h1>
            </div>
        </div>
    </div>
</header>
<!-- Search -->
<section id="action" class="py-4 mb-4 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-mid-6 ml-auto">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search">
                    <span class="input-group-btn">
                        <button class="btn btn-success">Search</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</section>


<!-- Clients -->
<section id="Clients">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card">
                    @if (!Model.Any())
                    {
                        <div class="card-header">
                            <h4>There are No Policies in the Database</h4>
                        </div>

                    }
                    else
                    {
                        <div class="card-header">
                            <h4>Policy Details</h4>
                        </div>

                        <table class="table table-striped">

                            <thead class="thead-dark">
                                <tr>
                                    <th>#</th>
                                    <th>Policy Name</th>
                                    <th>Amount</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var policy in Model)
                                {
                                    <tr>
                                        <td scope="row">@policy.Id</td>
                                        <td>@policy.Name</td>
                                        <td>@policy.Amount</td>
                                        <td>
                                            @Html.ActionLink("Details", "Details", "Policy", new { id = policy.Id }, new { @class = "btn btn-secondary" })
                                            @*@Html.ActionLink("Details", "ClientDetails", "Home", new { @class = "btn btn-secondary" })*@
                                            @*<a href="@Url.Action("ClientDetails","Home")" class="btn btn-secondary" new { id = customer.Cus_Id }, null>
                                                    <i class="fa fa-angle-double-right"></i> Details
                                                </a>*@
                                        </td>
                                    </tr>
                                }
                            </tbody>

                        </table>
                    }
                    <nav class="ml-4">
                        <ul class="pagination">
                            <li class="page-item disabled"><a href="#" class="page-link">Previous</a></li>
                            <li class="page-item active"><a href="#" class="page-link">1</a></li>
                            <li class="page-item"><a href="#" class="page-link">2</a></li>
                            <li class="page-item"><a href="#" class="page-link">3</a></li>
                            <li class="page-item"><a href="#" class="page-link">4</a></li>
                            <li class="page-item"><a href="#" class="page-link">5</a></li>
                            <li class="page-item"><a href="#" class="page-link">6</a></li>
                            <li class="page-item "><a href="#" class="page-link">>>></a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>